# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cb01b0147aab2290550d656fd88d3c81a8be44b26cb89e3367c851ebddd5bfa6382f435e0ed9e330fe47f47f73cf39fe63f3f188fe74530e61ac10e012ad30e2

test:
  secret_key_base: f8eaa6b1cf50394d2cd5f2d6053d82763eef6158dbeba35b0f12a68f4bdc20a2cb46e36d337b8ae0295e30b9773d3c08d188974a5fe34a0bd3178e359eef04ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
